### ISSUE TITLE
Request: Add some documentation to it

### ISSUE THREAD

**Issue by OsoianMarcel** [MetaMask/nonce-tracker#1]
It seems to be a great library, but PLEASE add documentation to it (or/and 1 example).
Anyone who will try to use it had to spend >30-60 (or even more) minutes to understand how it works.
Thanks.

**Comment by mcmire** [comment]
Documentation seems to have been added since this ticket was opened. We also have an example in the README. We could certainly do more, but I think this fulfills the desire here.
