### ISSUE TITLE
Gett TypeError: Cannot read properties of undefined (reading 'getLatestBlock') error

### ISSUE THREAD

**Issue by harensarma** [MetaMask/nonce-tracker#24]
Please add some documentation or example.. seems like great library, but hard to figureout the things..
I am getting this error: TypeError: Cannot read properties of undefined (reading 'getLatestBlock')

**Comment by Manel9999** [comment]
In my case is say: Error handling response: TypeError: Cannot read properties of undefined (reading 'vault')
  at <anonymous>:2:44.

When trying to restore seed phrase from vault decryptor for metamask. Any help please?

**Comment by mcmire** [comment]
If you could provide a more complete example of the code you're using, that would help us resolve your issue.

**Comment by Manel9999** [comment]
Hi! this is the code I am using: chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
})

But, look at the result data I am obtaining: {"data":"m3MHxNzgSoVDQ/oK4Ppqyyby/zLP+8CpIDZOr5GoTd9UpEmOyeYOZUmxEJEWjKil6W7gc1xqZJ+vSfDCDiEZ/mwibc3Jpt3ZsN/WJd1AfPlYrUqfWwLP3eyuIeoPxp3Ziq6jwA45qwlkqjBs9/sa8HFYvWrZcoiC9NX4RKRlotiCAWyP5gtbxuZZluGPxBbaPtQzFnWNT7p7NP34Eth0WKkKDlnXvmOw0enUZ6AeWHjhVN3j2Dw4kZr37oiEKOPpKjnS8+dG3OWBx9UvHJ0GoDRSclX6SAzmDF2A91YnQyQBtsgUknoe0mLdYfih/sOtWfgSAWMLs9+oJNivX4lEaXvIpZbUKg0G7LjosbHrAe0DE5jXWtJaa0/YRAPkQzmaokckGs4uySEPLWCidOhE+S1kyWcuPqQ+t6E0gR27aGVC6noQmKK+BpeQw2RgpvoMPxUSOLpAcra6Q1CJoljWVULlwWlf/asFeAb7M9UAxulWHTttjBnUlovb1URTOPIGrcmBdxKpVCr6WO4Nf/NdeyfSdACysF9Pg+60Hj21+Py+Tq1cxAlv6GGlWAOHGybXCbdDgU7dSzVJva90g7/0wfbpSaH6RWauZSIuyb58GZdby934ZnlLPlSCgrVIA+aE8ahTJhj4SX+BPCHJIm8nWq6ZeKVSeL4xX11Hzy7pIzXGIgm+NFngP+0ox7iolGZDxocWBEGCSNQS7tN1G7UJpa4bV2dWVuKwvLgvEZVl+yc7hw3jdhajLN3QzIiXbWofy/mwq1nuS7qlccmic7Hlf1Fz7s8BQqSjLHYzDrJdWYeE8e18xI8rVZgLIAjlJ6IJvIDKU3RATc/VEgO1hmefIk0Db/UiQcBMy4TBZPki+4LNBN39mekBwYlZk7l25BbMTqqFOE/FHZ9Srs23xdQSULyV2oFz0IbfnHwcEO7fnhApOInRKzZCzefjUYO35bn3fmWNL9SF3AMefQNByxa2fGtbvZikgbtJemRnyWOCObHSyrm96+qTBsdiOzpwsFiweL8s4VHlGb1vjgSU+BV0uz1AoeC9Ygo9mKEtBIGKC4B71wSJEu1iIIYdEbz+E9x3xiM0Yv1KbRUBAgNxrOena5Lvp75r5xYs3diCnvZ5JEwNst2lv7PCIWpFDubCGXJ8w/doCxrAFcahuTHdtok8hXx2/fTXfm2zIbMy/oM0I94nnMfFHyRbPOFnjZ3CY6vVWZBhYHIe3qFh0rm1711yubeiIsvNqbZ90uBBnNM2dO2ayrJnDZlwBv3GvuX+cts3Vw==","iv":"EexXeAXvKIOw0J16sZtNNA==","salt":"HvX+T/zzkpwjdmqdh7+DQOsEhbWKwF9UEk1ziKp/aD8="}

1- When I decrypt this data on the vault and I am logeed in the new wallet ( the duplicated one) , the result is lots of numbers which make no sense as there are no words related to the seed phrase
2- If I am not logged in any wallet, this is the result: Error handling response: TypeError: Cannot read properties of undefined (reading 'vault')
  at <anonymous>:2:44

Please, I would be so grateful if you could help me with this. Many thanks

**Comment by mcmire** [comment]
A couple things:

1. Did this vault data come from your account? You should never, _ever_ post your vault data publicly like that, because it contains your secret recovery phrase (albeit encrypted, but still). I redacted it for you, but please be careful in the future.
2. This is the repo for `nonce-tracker`. I imagine you're talking about the vault decryptor. I'm going to close this issue because it's not related, but there are other people who've had this issue. We don't have a fix right now but I will look into this when I get a chance.
