### ISSUE TITLE
ci: Migrate from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by legobeat** [MetaMask/nonce-tracker#33]
This package should have workflows lifted from https://github.com/MetaMask/metamask-module-template/tree/main/.github/workflows instead of existing CircleCI jobs.

**Comment by Najamulhassan3383** [comment]
Hi!
I am new to open source contribution and this will be my first contribution. If you have free time, can you plz explain the issue, what and how can i solve this?
It will be highly appreciated . Thanks

**Comment by SurajAnand88** [comment]
I've opened a PR for this issue
